# Generated by Django 5.2.9 on 2026-01-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=220, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=120, unique=True
            ),
        ),
    ]
