# Generated by Django 5.2.9 on 2026-02-04 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assessment_hotline_institution_relaxationmethod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'created_at'], name='article_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'is_published'], name='article_cat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_published', 'category'], name='assessment_pub_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationticket',
            index=models.Index(fields=['user', 'created_at'], name='ticket_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationticket',
            index=models.Index(fields=['status', 'created_at'], name='ticket_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationticket',
            index=models.Index(fields=['assigned_to', 'status'], name='ticket_assigned_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hotline',
            index=models.Index(fields=['region_type', 'is_emergency'], name='hotline_region_emerg_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['region_type'], name='institution_region_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['province', 'city'], name='institution_location_idx'),
        ),
        migrations.AddIndex(
            model_name='relaxationlog',
            index=models.Index(fields=['user', 'practiced_at'], name='relaxlog_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='relaxationreminder',
            index=models.Index(fields=['user', 'is_active'], name='reminder_user_active_idx'),
        ),
    ]
